apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gke-external-gateway
  namespace: non-application
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      namespaces:
        from: Same
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
