name: Triggered Workflow in Target Repo

on:
  repository_dispatch:
    types: [pr-created]

jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get the developer branch name
        run: echo "BRANCH_NAME=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV

      - name: Clone the target repository
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.PAT }}@github.com/AshishCloudphysician/Test-poc-demo-private.git target-repo
          cd target-repo
          git fetch --prune --unshallow

      - name: Check if the developer branch is behind `master`
        run: |
          cd target-repo
          git fetch origin master
          if git rev-list --left-right origin/${{ env.BRANCH_NAME }}...origin/master | grep '>'; then
            echo "branch_behind=true" >> $GITHUB_ENV
          else
            echo "branch_behind=false" >> $GITHUB_ENV
          fi

      - name: Notify Google Chat if the branch is outdated
        if: env.branch_behind == 'true'
        run: |
          curl -X POST -H 'Content-Type: application/json' --data '{
            "text": "⚠️ *Branch Outdated:* PR created on (`${{ env.BRANCH_NAME }}`) is behind `master`. Please update it before merging."
          }' "https://chat.googleapis.com/v1/spaces/AAAA7ZrcrhM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Adax0wiCdrkex17FhC6rTLXtzUMRvMZgFtQpSYZ6hdk"

      - name: Fail the pipeline if the developer branch is outdated
        if: env.branch_behind == 'true'
        run: |
          echo "❌ Developer branch is behind `master`. Please rebase."
          exit 1

      - name: Notify Google Chat if the developer branch is up-to-date
        if: env.branch_behind == 'false'
        run: |
          curl -X POST -H 'Content-Type: application/json' --data '{
            "text": "✅ *Developer Branch Up-to-Date:* PR created on (`${{ env.BRANCH_NAME }}`) is up-to-date with `master`."
          }' "https://chat.googleapis.com/v1/spaces/AAAA7ZrcrhM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Adax0wiCdrkex17FhC6rTLXtzUMRvMZgFtQpSYZ6hdk"
