name: Auto Merge Master to poc-demo

on:
  push:
    branches:
      - master  # Trigger workflow when master is updated

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: AshishCloudphysician/Test-poc-demo-private
          fetch-depth: 0  # Fetch full history for proper merging
          token: ${{ secrets.PAT }}  # Use a PAT with write access

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge master into poc-demo
        run: |
          git checkout poc-demo
          git pull origin poc-demo --rebase
          git merge origin/master || true

          # Ignore .github/workflows folder during merge
          git checkout --ours .github/workflows
          git add .github/workflows

          # Handle merge conflicts (prefer master’s changes for other files)
          if git diff --name-only --diff-filter=U | grep .; then
            git diff --name-only --diff-filter=U | while read file; do
              if [[ "$file" != ".github/workflows/"* ]]; then
                git checkout --theirs "$file"
                git add "$file"
              fi
            done
            git commit -m "Auto-resolved merge conflicts (excluding .github/workflows)"
          fi

      - name: Push changes to poc-demo (only if changes exist)
        run: |
          git diff --quiet HEAD origin/poc-demo || git push origin poc-demo



